"""add_units

Revision ID: 5cb7d4e9230c
Revises: a07447cd8896
Create Date: 2019-06-26 10:44:04.356740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cb7d4e9230c'
down_revision = 'a07447cd8896'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('unit', sa.String(), nullable=False, server_default='number'))
    connection = op.get_bind()
    connection.execute("UPDATE questions SET unit = 'cm^{-2}' WHERE id = 37;")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'unit')
    # ### end Alembic commands ###
